- name: Install psql10 rpm
  yum: 
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes

- name: Install psql10
  yum:
    name:  postgresql10
    state: present
  become: yes

